export interface Project {
  slug: string;
  index: string;
  title: string;
  category: string;
  description: string;
  tags: string[];
  visualLabel: string;
  image?: string;
}

export interface UpcomingProject {
  slug: string;
  id?: string;
  title: string;
  description: string;
  stage: 'researching' | 'designing' | 'developing';
  direction: string;
}

export interface ProcessStep {
  number: string;
  name: string;
  description: string;
}

// ── Selected Work Projects ───────────────────────────────────────────────────
export const SELECTED_WORK: Project[] = [
  {
    slug: 'buildfin',
    index: '01',
    title: 'BuildFin',
    category: 'CONSTRUCTION FINANCE',
    description:
      'A construction financial intelligence system that connects financial activity with actual project progress, revealing cost deviations and emerging risks before they escalate into larger financial problems.',
    tags: ['CONSTRUCTION FINANCE', 'FINANCIAL INTELLIGENCE', 'RISK & DEVIATION ANALYSIS'],
    visualLabel: 'FINANCIAL DEVIATION MODEL · BUILDFIN',
    image: '/images/buildfin-preview.png',
  },
  {
    slug: 'microtrace',
    index: '02',
    title: 'MicroTrace',
    category: 'ENVIRONMENTAL TECHNOLOGY',
    description:
      'An end-to-end computer vision system that detects, classifies, and quantifies microplastic contamination in water samples — translating raw microscope images into contamination risk scores and structured reports.',
    tags: ['DISTRIBUTED TRACING', 'REAL-TIME SYSTEMS', 'OBSERVABILITY'],
    visualLabel: 'CONTAMINATION MAPPING · MICROTRACE',
    image: '/images/microtrace-preview.png',
  },
];

// ── Upcoming Work Projects ───────────────────────────────────────────────────
export const UPCOMING_WORK: UpcomingProject[] = [
  {
    slug: 'buildrev',
    title: '01 — BuildRev',
    description:
      'Exploring a new layer of engineering intelligence between design information and the decisions engineers make.',
    stage: 'researching',
    direction: 'ENGINEERING REVIEW · DESIGN INTELLIGENCE · DECISION SUPPORT',
  },
  {
    slug: 'habitus',
    title: '02 — Habitus',
    description:
      'Exploring physiology-informed decision support for exercise, recovery, and rehabilitation — translating personal health signals into clearer, more adaptive physical activity decisions.',
    stage: 'researching',
    direction: 'PHYSIOLOGY · RECOVERY · REHABILITATION · DECISION SUPPORT',
  },
];

// ── How I Build (7 Principles) ────────────────────────────────────────────────
export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: '01',
    name: 'START WITH THE PROBLEM, NOT THE SOLUTION.',
    description:
      'Understand what actually needs solving before deciding what to build.',
  },
  {
    number: '02',
    name: 'LEARN THE DOMAIN BEFORE DESIGNING THE SYSTEM.',
    description:
      'The environment, people, constraints, and workflows should shape the system—not the technology.',
  },
  {
    number: '03',
    name: 'CHALLENGE ASSUMPTIONS EARLY.',
    description:
      "Treat early ideas as hypotheses. Question them, test alternatives, and remove what doesn't hold up.",
  },
  {
    number: '04',
    name: 'DESIGN FOR CLARITY AND EXPLAINABILITY.',
    description:
      'Build systems whose behaviour can be understood, traced, and validated—especially when they influence real-world decisions.',
  },
  {
    number: '05',
    name: 'LET ARCHITECTURE GUIDE IMPLEMENTATION.',
    description:
      'Define the system before writing the code. Technology should express the design, not determine it.',
  },
  {
    number: '06',
    name: 'VALIDATE IDEAS, NOT JUST CODE.',
    description:
      "A working implementation doesn't prove that the underlying idea is right. Test the assumptions behind it.",
  },
  {
    number: '07',
    name: 'CARRY EVERY LESSON FORWARD.',
    description:
      'Every project should change how the next one is approached.',
  },
];

// ── Complete Technology Stack Inventory ───────────────────────────────────────

export interface TechItem {
  id: string;
  name: string;
  category: string;
  categoryId: string;
  categoryNumber: string;
  shortDesc: string;
  brandColor: string;
  badgeBg: string;
  badgeFg: string;
  symbol: string;
  faceIndex: number; // which of the 12 Megaminx faces this belongs to
  slotIndex: number; // 0 = center pentagon, 1..5 = outer trapezoid facets
}

export interface ToolCategory {
  id: string;
  number: string;
  label: string;
  description: string;
  faceIndex: number;
  techs: TechItem[];
}

export const ALL_TECHNOLOGIES: TechItem[] = [
  // 01 — LANGUAGES (Face 0)
  {
    id: 'python',
    name: 'Python',
    category: 'LANGUAGES',
    categoryId: 'languages',
    categoryNumber: '01',
    shortDesc: 'Core language for systems, asynchronous backend services, and deep learning pipelines.',
    brandColor: '#3776AB',
    badgeBg: '#3776AB',
    badgeFg: '#FFD438',
    symbol: 'Py',
    faceIndex: 0,
    slotIndex: 0,
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    category: 'LANGUAGES',
    categoryId: 'languages',
    categoryNumber: '01',
    shortDesc: 'Type-safe JavaScript superset for scalable, mission-critical application architectures.',
    brandColor: '#3178C6',
    badgeBg: '#3178C6',
    badgeFg: '#FFFFFF',
    symbol: 'TS',
    faceIndex: 0,
    slotIndex: 1,
  },

  // 02 — FRONTEND (Face 1)
  {
    id: 'react',
    name: 'React',
    category: 'FRONTEND',
    categoryId: 'frontend',
    categoryNumber: '02',
    shortDesc: 'Component-driven declarative UI library for high-responsiveness web apps.',
    brandColor: '#00D8FF',
    badgeBg: '#00D8FF',
    badgeFg: '#000000',
    symbol: '⚛',
    faceIndex: 1,
    slotIndex: 0,
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    category: 'FRONTEND',
    categoryId: 'frontend',
    categoryNumber: '02',
    shortDesc: 'Full-stack React framework with SSR, App Router, and Turbopack optimization.',
    brandColor: '#000000',
    badgeBg: '#000000',
    badgeFg: '#FFFFFF',
    symbol: 'N',
    faceIndex: 1,
    slotIndex: 1,
  },
  {
    id: 'react-native',
    name: 'React Native (Expo)',
    category: 'FRONTEND',
    categoryId: 'frontend',
    categoryNumber: '02',
    shortDesc: 'Cross-platform native mobile development framework for iOS and Android.',
    brandColor: '#4630EB',
    badgeBg: '#4630EB',
    badgeFg: '#FFFFFF',
    symbol: 'EX',
    faceIndex: 1,
    slotIndex: 2,
  },
  {
    id: 'vite',
    name: 'Vite',
    category: 'FRONTEND',
    categoryId: 'frontend',
    categoryNumber: '02',
    shortDesc: 'Next-generation ultra-fast frontend build tooling and HMR dev server.',
    brandColor: '#646CFF',
    badgeBg: '#646CFF',
    badgeFg: '#FFD500',
    symbol: '⚡',
    faceIndex: 1,
    slotIndex: 3,
  },
  {
    id: 'tailwind-css',
    name: 'Tailwind CSS',
    category: 'FRONTEND',
    categoryId: 'frontend',
    categoryNumber: '02',
    shortDesc: 'Utility-first CSS framework for rapid, bespoke responsive user interfaces.',
    brandColor: '#0EA5E9',
    badgeBg: '#0EA5E9',
    badgeFg: '#FFFFFF',
    symbol: '≈',
    faceIndex: 1,
    slotIndex: 4,
  },
  {
    id: 'css-modules',
    name: 'CSS Modules',
    category: 'FRONTEND',
    categoryId: 'frontend',
    categoryNumber: '02',
    shortDesc: 'Scoped CSS styling architecture preventing global selector collisions.',
    brandColor: '#2563EB',
    badgeBg: '#2563EB',
    badgeFg: '#FFFFFF',
    symbol: 'CSS',
    faceIndex: 1,
    slotIndex: 5,
  },

  // 03 — BACKEND (Face 2)
  {
    id: 'fastapi',
    name: 'FastAPI',
    category: 'BACKEND',
    categoryId: 'backend',
    categoryNumber: '03',
    shortDesc: 'High-performance asynchronous Python API framework with automatic OpenAPI docs.',
    brandColor: '#059669',
    badgeBg: '#059669',
    badgeFg: '#FFFFFF',
    symbol: '⚡',
    faceIndex: 2,
    slotIndex: 0,
  },
  {
    id: 'uvicorn-gunicorn',
    name: 'Uvicorn / Gunicorn',
    category: 'BACKEND',
    categoryId: 'backend',
    categoryNumber: '03',
    shortDesc: 'Lightning-fast ASGI / WSGI production application server runtimes.',
    brandColor: '#2C3E50',
    badgeBg: '#2C3E50',
    badgeFg: '#4ADE80',
    symbol: 'WS',
    faceIndex: 2,
    slotIndex: 1,
  },

  // 04 — DATABASE & ORM (Face 3)
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'DATABASE & ORM',
    categoryId: 'database-orm',
    categoryNumber: '04',
    shortDesc: 'Enterprise-grade relational database with robust ACID transactions and indexing.',
    brandColor: '#336791',
    badgeBg: '#336791',
    badgeFg: '#FFFFFF',
    symbol: 'PG',
    faceIndex: 3,
    slotIndex: 0,
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    category: 'DATABASE & ORM',
    categoryId: 'database-orm',
    categoryNumber: '04',
    shortDesc: 'Self-contained, serverless zero-configuration embedded SQL database engine.',
    brandColor: '#0284C7',
    badgeBg: '#0284C7',
    badgeFg: '#FFFFFF',
    symbol: 'SQL',
    faceIndex: 3,
    slotIndex: 1,
  },
  {
    id: 'prisma-orm',
    name: 'Prisma ORM',
    category: 'DATABASE & ORM',
    categoryId: 'database-orm',
    categoryNumber: '04',
    shortDesc: 'Next-generation type-safe Node.js and TypeScript ORM with schema migrations.',
    brandColor: '#1E293B',
    badgeBg: '#1E293B',
    badgeFg: '#38BDF8',
    symbol: '▲',
    faceIndex: 3,
    slotIndex: 2,
  },
  {
    id: 'redis-upstash',
    name: 'Redis',
    category: 'DATABASE & ORM',
    categoryId: 'database-orm',
    categoryNumber: '04',
    shortDesc: 'Ultra-low-latency in-memory data store for caching and pub/sub message queues.',
    brandColor: '#DC2626',
    badgeBg: '#DC2626',
    badgeFg: '#FFFFFF',
    symbol: 'RD',
    faceIndex: 3,
    slotIndex: 3,
  },

  // 05 — SECURITY & AUTH (Face 4)
  {
    id: 'authjs',
    name: 'Auth.js / NextAuth.js',
    category: 'SECURITY & AUTH',
    categoryId: 'security-validation',
    categoryNumber: '05',
    shortDesc: 'Complete authentication solution for Next.js applications and secure sessions.',
    brandColor: '#6D28D9',
    badgeBg: '#6D28D9',
    badgeFg: '#FFFFFF',
    symbol: '🔒',
    faceIndex: 4,
    slotIndex: 0,
  },
  {
    id: 'jwt',
    name: 'JWT',
    category: 'SECURITY & AUTH',
    categoryId: 'security-validation',
    categoryNumber: '05',
    shortDesc: 'Compact stateless JSON Web Tokens for secure cross-service API authorization.',
    brandColor: '#C026D3',
    badgeBg: '#C026D3',
    badgeFg: '#FFFFFF',
    symbol: 'JWT',
    faceIndex: 4,
    slotIndex: 1,
  },
  {
    id: 'oauth2',
    name: 'OAuth2',
    category: 'SECURITY & AUTH',
    categoryId: 'security-validation',
    categoryNumber: '05',
    shortDesc: 'Standard delegated authorization protocol for third-party identity providers.',
    brandColor: '#2563EB',
    badgeBg: '#2563EB',
    badgeFg: '#FFFFFF',
    symbol: 'OA',
    faceIndex: 4,
    slotIndex: 2,
  },
  {
    id: 'csp',
    name: 'CSP',
    category: 'SECURITY & AUTH',
    categoryId: 'security-validation',
    categoryNumber: '05',
    shortDesc: 'Content Security Policy headers mitigating XSS and malicious script injections.',
    brandColor: '#475569',
    badgeBg: '#475569',
    badgeFg: '#FFFFFF',
    symbol: 'CSP',
    faceIndex: 4,
    slotIndex: 3,
  },
  {
    id: 'sentry',
    name: 'Sentry',
    category: 'SECURITY & AUTH',
    categoryId: 'security-validation',
    categoryNumber: '05',
    shortDesc: 'Real-time telemetry, crash reporting, and distributed stack trace tracking.',
    brandColor: '#FB7185',
    badgeBg: '#362D59',
    badgeFg: '#FB7185',
    symbol: 'S',
    faceIndex: 4,
    slotIndex: 4,
  },

  // 06 — VALIDATION & EMAIL (Face 5)
  {
    id: 'zod',
    name: 'Zod',
    category: 'VALIDATION & EMAIL',
    categoryId: 'validation-email',
    categoryNumber: '06',
    shortDesc: 'TypeScript-first schema declaration with static type inference and runtime parsing.',
    brandColor: '#3068B7',
    badgeBg: '#3068B7',
    badgeFg: '#93C5FD',
    symbol: 'Z',
    faceIndex: 5,
    slotIndex: 0,
  },
  {
    id: 'resend',
    name: 'Resend',
    category: 'VALIDATION & EMAIL',
    categoryId: 'validation-email',
    categoryNumber: '06',
    shortDesc: 'Transactional email API built for high deliverability and React email templates.',
    brandColor: '#000000',
    badgeBg: '#000000',
    badgeFg: '#FFFFFF',
    symbol: '✉',
    faceIndex: 5,
    slotIndex: 1,
  },

  // 07 — DATA VISUALIZATION (Face 6)
  {
    id: 'recharts',
    name: 'Recharts',
    category: 'DATA VISUALIZATION',
    categoryId: 'data-visualization',
    categoryNumber: '07',
    shortDesc: 'Redefined composable charting library built on React components and SVG.',
    brandColor: '#06B6D4',
    badgeBg: '#06B6D4',
    badgeFg: '#FFFFFF',
    symbol: '📈',
    faceIndex: 6,
    slotIndex: 0,
  },
  {
    id: 'chartjs',
    name: 'Chart.js',
    category: 'DATA VISUALIZATION',
    categoryId: 'data-visualization',
    categoryNumber: '07',
    shortDesc: 'Lightweight HTML5 Canvas charting for animated data representations.',
    brandColor: '#F43F5E',
    badgeBg: '#F43F5E',
    badgeFg: '#FFFFFF',
    symbol: '📊',
    faceIndex: 6,
    slotIndex: 1,
  },
  {
    id: 'd3',
    name: 'D3',
    category: 'DATA VISUALIZATION',
    categoryId: 'data-visualization',
    categoryNumber: '07',
    shortDesc: 'Custom data-driven document manipulation and complex geometric visualizations.',
    brandColor: '#EA580C',
    badgeBg: '#EA580C',
    badgeFg: '#FFFFFF',
    symbol: 'D3',
    faceIndex: 6,
    slotIndex: 2,
  },

  // 08 — ML / AI (Face 7)
  {
    id: 'pytorch',
    name: 'PyTorch',
    category: 'ML / AI',
    categoryId: 'ml-ai',
    categoryNumber: '08',
    shortDesc: 'State-of-the-art tensor computation and deep neural network training framework.',
    brandColor: '#EA580C',
    badgeBg: '#EA580C',
    badgeFg: '#FFFFFF',
    symbol: '🔥',
    faceIndex: 7,
    slotIndex: 0,
  },
  {
    id: 'yolov8',
    name: 'YOLOv8-nano (Ultralytics)',
    category: 'ML / AI',
    categoryId: 'ml-ai',
    categoryNumber: '08',
    shortDesc: 'Ultra-fast object detection and segmentation architecture optimized for inference.',
    brandColor: '#2563EB',
    badgeBg: '#2563EB',
    badgeFg: '#FBBF24',
    symbol: 'Y8',
    faceIndex: 7,
    slotIndex: 1,
  },

  // 09 — COMPUTER VISION & DATA (Face 8)
  {
    id: 'opencv',
    name: 'OpenCV',
    category: 'COMPUTER VISION & DATA',
    categoryId: 'computer-vision',
    categoryNumber: '09',
    shortDesc: 'Comprehensive real-time computer vision, image processing, and video analytics library.',
    brandColor: '#6366F1',
    badgeBg: '#6366F1',
    badgeFg: '#FFFFFF',
    symbol: 'CV',
    faceIndex: 8,
    slotIndex: 0,
  },
  {
    id: 'mediapipe',
    name: 'MediaPipe',
    category: 'COMPUTER VISION & DATA',
    categoryId: 'computer-vision',
    categoryNumber: '09',
    shortDesc: 'Cross-platform ML solutions for real-time facial landmarks, hand, and pose tracking.',
    brandColor: '#0D9488',
    badgeBg: '#0D9488',
    badgeFg: '#FFFFFF',
    symbol: 'MP',
    faceIndex: 8,
    slotIndex: 1,
  },
  {
    id: 'numpy',
    name: 'NumPy',
    category: 'COMPUTER VISION & DATA',
    categoryId: 'computer-vision',
    categoryNumber: '09',
    shortDesc: 'High-performance mathematical array operations and linear algebra routines.',
    brandColor: '#0284C7',
    badgeBg: '#0284C7',
    badgeFg: '#FFFFFF',
    symbol: 'NP',
    faceIndex: 8,
    slotIndex: 2,
  },
  {
    id: 'pandas',
    name: 'Pandas',
    category: 'COMPUTER VISION & DATA',
    categoryId: 'computer-vision',
    categoryNumber: '09',
    shortDesc: 'Structured tabular data analysis, dataframe manipulation, and dataset cleaning.',
    brandColor: '#1E1B4B',
    badgeBg: '#1E1B4B',
    badgeFg: '#E0E7FF',
    symbol: 'PD',
    faceIndex: 8,
    slotIndex: 3,
  },

  // 10 — TRAINING & INFERENCE INFRASTRUCTURE (Face 9)
  {
    id: 'google-colab',
    name: 'Google Colab (T4 GPU)',
    category: 'TRAINING & INFRASTRUCTURE',
    categoryId: 'training-infra',
    categoryNumber: '10',
    shortDesc: 'Cloud-hosted Jupyter notebook execution with NVIDIA T4 GPU tensor acceleration.',
    brandColor: '#D97706',
    badgeBg: '#D97706',
    badgeFg: '#FFFFFF',
    symbol: 'CO',
    faceIndex: 9,
    slotIndex: 0,
  },
  {
    id: 'nvidia-rtx-5050',
    name: 'NVIDIA RTX 5050 (8GB VRAM)',
    category: 'TRAINING & INFRASTRUCTURE',
    categoryId: 'training-infra',
    categoryNumber: '10',
    shortDesc: 'Dedicated local GPU hardware for real-time model inference and CUDA development.',
    brandColor: '#65A30D',
    badgeBg: '#65A30D',
    badgeFg: '#FFFFFF',
    symbol: 'NV',
    faceIndex: 9,
    slotIndex: 1,
  },
  {
    id: 'cuda',
    name: 'CUDA 12.8',
    category: 'TRAINING & INFRASTRUCTURE',
    categoryId: 'training-infra',
    categoryNumber: '10',
    shortDesc: 'NVIDIA parallel computing platform and programming model for tensor execution.',
    brandColor: '#16A34A',
    badgeBg: '#16A34A',
    badgeFg: '#FFFFFF',
    symbol: 'CU',
    faceIndex: 9,
    slotIndex: 2,
  },

  // 11 — DATASET TOOLS & EXTERNAL APIs (Face 10)
  {
    id: 'roboflow',
    name: 'Roboflow',
    category: 'DATASET TOOLS & APIs',
    categoryId: 'dataset-apis',
    categoryNumber: '11',
    shortDesc: 'Automated computer vision dataset labeling, augmentation, and model deployment.',
    brandColor: '#7C3AED',
    badgeBg: '#7C3AED',
    badgeFg: '#FFFFFF',
    symbol: 'RF',
    faceIndex: 10,
    slotIndex: 0,
  },
  {
    id: 'roboflow-universe',
    name: 'Roboflow Universe',
    category: 'DATASET TOOLS & APIs',
    categoryId: 'dataset-apis',
    categoryNumber: '11',
    shortDesc: 'Open dataset repository and pre-trained computer vision model community.',
    brandColor: '#7C3AED',
    badgeBg: '#7C3AED',
    badgeFg: '#FFFFFF',
    symbol: 'RU',
    faceIndex: 10,
    slotIndex: 1,
  },
  {
    id: 'openfda-api',
    name: 'OpenFDA API',
    category: 'DATASET TOOLS & APIs',
    categoryId: 'dataset-apis',
    categoryNumber: '11',
    shortDesc: 'Public REST API for biomedical querying of adverse drug events and clearances.',
    brandColor: '#0284C7',
    badgeBg: '#0284C7',
    badgeFg: '#FFFFFF',
    symbol: 'FDA',
    faceIndex: 10,
    slotIndex: 2,
  },
  {
    id: 'rxnorm-api',
    name: 'RxNorm API',
    category: 'DATASET TOOLS & APIs',
    categoryId: 'dataset-apis',
    categoryNumber: '11',
    shortDesc: 'Standardized pharmacological nomenclature and drug interaction knowledge graph.',
    brandColor: '#0F766E',
    badgeBg: '#0F766E',
    badgeFg: '#FFFFFF',
    symbol: 'Rx',
    faceIndex: 10,
    slotIndex: 3,
  },
  {
    id: 'fcm',
    name: 'Firebase Cloud Messaging',
    category: 'DATASET TOOLS & APIs',
    categoryId: 'dataset-apis',
    categoryNumber: '11',
    shortDesc: 'Cross-platform push messaging service for real-time mobile and web notifications.',
    brandColor: '#D97706',
    badgeBg: '#D97706',
    badgeFg: '#FFFFFF',
    symbol: '🔥',
    faceIndex: 10,
    slotIndex: 4,
  },

  // 12 — TOOLING (Face 11)
  {
    id: 'docker',
    name: 'Docker',
    category: 'TOOLING',
    categoryId: 'tooling',
    categoryNumber: '12',
    shortDesc: 'Container virtualization for reproducible, isolated deployment environments.',
    brandColor: '#0284C7',
    badgeBg: '#0284C7',
    badgeFg: '#FFFFFF',
    symbol: 'DK',
    faceIndex: 11,
    slotIndex: 0,
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'TOOLING',
    categoryId: 'tooling',
    categoryNumber: '12',
    shortDesc: 'Collaborative code hosting, pull request workflows, and automated CI/CD actions.',
    brandColor: '#181717',
    badgeBg: '#181717',
    badgeFg: '#FFFFFF',
    symbol: 'GH',
    faceIndex: 11,
    slotIndex: 1,
  },
  {
    id: 'git',
    name: 'Git',
    category: 'TOOLING',
    categoryId: 'tooling',
    categoryNumber: '12',
    shortDesc: 'Distributed version control system tracking codebase history and branching.',
    brandColor: '#EA580C',
    badgeBg: '#EA580C',
    badgeFg: '#FFFFFF',
    symbol: 'GIT',
    faceIndex: 11,
    slotIndex: 2,
  },
  {
    id: 'figma',
    name: 'Figma',
    category: 'TOOLING',
    categoryId: 'tooling',
    categoryNumber: '12',
    shortDesc: 'Vector interface design, component library architecture, and interactive prototyping.',
    brandColor: '#E11D48',
    badgeBg: '#E11D48',
    badgeFg: '#FFFFFF',
    symbol: 'FG',
    faceIndex: 11,
    slotIndex: 3,
  },
];

// ── 12 Grouped Categories for Secondary Directory ─────────────────────────────
export const TECH_CATEGORIES: ToolCategory[] = [
  {
    id: 'languages',
    number: '01',
    label: 'LANGUAGES',
    description: 'Core programming languages for systems, backend services, and application logic.',
    faceIndex: 0,
    techs: ALL_TECHNOLOGIES.filter((t) => t.categoryId === 'languages'),
  },
  {
    id: 'frontend',
    number: '02',
    label: 'FRONTEND',
    description: 'Component-driven web frameworks, mobile interfaces, and styling engines.',
    faceIndex: 1,
    techs: ALL_TECHNOLOGIES.filter((t) => t.categoryId === 'frontend'),
  },
  {
    id: 'backend',
    number: '03',
    label: 'BACKEND',
    description: 'High-performance asynchronous API services and WSGI/ASGI production servers.',
    faceIndex: 2,
    techs: ALL_TECHNOLOGIES.filter((t) => t.categoryId === 'backend'),
  },
  {
    id: 'database-orm',
    number: '04',
    label: 'DATABASE & ORM',
    description: 'Relational storage, embedded engines, distributed caching, and type-safe query layers.',
    faceIndex: 3,
    techs: ALL_TECHNOLOGIES.filter((t) => t.categoryId === 'database-orm'),
  },
  {
    id: 'security-validation',
    number: '05',
    label: 'SECURITY & AUTH',
    description: 'Identity verification, token authorization, strict runtime validation, and error telemetry.',
    faceIndex: 4,
    techs: ALL_TECHNOLOGIES.filter((t) => t.categoryId === 'security-validation'),
  },
  {
    id: 'validation-email',
    number: '06',
    label: 'VALIDATION & EMAIL',
    description: 'Runtime type checking and transactional messaging delivery infrastructure.',
    faceIndex: 5,
    techs: ALL_TECHNOLOGIES.filter((t) => t.categoryId === 'validation-email'),
  },
  {
    id: 'data-visualization',
    number: '07',
    label: 'DATA VISUALIZATION',
    description: 'Declarative charting, SVG/Canvas rendering, and custom quantitative metric displays.',
    faceIndex: 6,
    techs: ALL_TECHNOLOGIES.filter((t) => t.categoryId === 'data-visualization'),
  },
  {
    id: 'ml-ai',
    number: '08',
    label: 'ML / AI',
    description: 'Deep neural networks, real-time object detection models, and tensor computation pipelines.',
    faceIndex: 7,
    techs: ALL_TECHNOLOGIES.filter((t) => t.categoryId === 'ml-ai'),
  },
  {
    id: 'computer-vision',
    number: '09',
    label: 'COMPUTER VISION & DATA',
    description: 'Image processing, landmark tracking, tensor computations, and tabular manipulation.',
    faceIndex: 8,
    techs: ALL_TECHNOLOGIES.filter((t) => t.categoryId === 'computer-vision'),
  },
  {
    id: 'training-infra',
    number: '10',
    label: 'TRAINING & INFRASTRUCTURE',
    description: 'Hardware acceleration, GPU tensor cores, and CUDA execution runtimes.',
    faceIndex: 9,
    techs: ALL_TECHNOLOGIES.filter((t) => t.categoryId === 'training-infra'),
  },
  {
    id: 'dataset-apis',
    number: '11',
    label: 'DATASET TOOLS & APIs',
    description: 'Dataset annotation, computer vision hubs, and standardized biomedical APIs.',
    faceIndex: 10,
    techs: ALL_TECHNOLOGIES.filter((t) => t.categoryId === 'dataset-apis'),
  },
  {
    id: 'tooling',
    number: '12',
    label: 'TOOLING',
    description: 'Source control, containerization environments, interface design, and deployment pipelines.',
    faceIndex: 11,
    techs: ALL_TECHNOLOGIES.filter((t) => t.categoryId === 'tooling'),
  },
];
